#===========================================================================================
all: geohash

geohash:
	g++ -o geohash-encoder -O2 -Wall -W -ansi -pedantic geohash_encoder.cpp geohash_test.cpp

clean:
	rm -rf geohash-encoder
#===========================================================================================
